M48
; DRILL file {KiCad 8.0.7} date 2025-01-11T17:49:51-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-11T17:49:51-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X139.51Y-85.8
X145.29Y-85.8
T2
X118.725Y-82.315
X122.975Y-82.315
T3
X114.85Y-115.91
X114.85Y-127.34
M30
